# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Тут значения в основном подзаточено для графической карты NVIDIA.
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps

# Screenshot
env = HYPRSHOT_DIR,$HOME/Изображения/Screenshots/

# Theme
#env = GTK_THEME,
